//MIT License
//
//Copyright (c) 2021 mohamedSulaimanAlmarzooqi
//
//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files (the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions:
//
//The above copyright notice and this permission notice shall be included in all
//copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//SOFTWARE.
//
package synthizer

/*
#include <synthizer.h>
#include <synthizer_constants.h>
#include <stdlib.h>
*/
import "C"

type LogLevel C.int

const (
	LOG_LEVEL_ERROR LogLevel = C.SYZ_LOG_LEVEL_ERROR
	LOG_LEVEL_WARN = C.SYZ_LOG_LEVEL_WARN
	LOG_LEVEL_INFO = C.SYZ_LOG_LEVEL_INFO
	LOG_LEVEL_DEBUG = C.SYZ_LOG_LEVEL_DEBUG
)

type LoggingBackend C.int

const (
	LOGGING_BACKEND_NONE LoggingBackend = C.SYZ_LOGGING_BACKEND_NONE
	LOGGING_BACKEND_STDERR = C.SYZ_LOGGING_BACKEND_STDERR
)

type OBJECT_TYPE C.int

const (
	OTYPE_CONTEXT OBJECT_TYPE = C.SYZ_OTYPE_CONTEXT
	OTYPE_BUFFER = C.SYZ_OTYPE_BUFFER
	OTYPE_BUFFER_GENERATOR = C.SYZ_OTYPE_BUFFER_GENERATOR
	OTYPE_STREAMING_GENERATOR = C.SYZ_OTYPE_STREAMING_GENERATOR
	OTYPE_NOISE_GENERATOR = C.SYZ_OTYPE_NOISE_GENERATOR
	OTYPE_DIRECT_SOURCE = C.SYZ_OTYPE_DIRECT_SOURCE
	OTYPE_ANGULAR_PANNED_SOURCE = C.SYZ_OTYPE_ANGULAR_PANNED_SOURCE
	OTYPE_SCALAR_PANNED_SOURCE = C.SYZ_OTYPE_SCALAR_PANNED_SOURCE
	OTYPE_SOURCE_3D = C.SYZ_OTYPE_SOURCE_3D
	OTYPE_GLOBAL_ECHO = C.SYZ_OTYPE_GLOBAL_ECHO
	OTYPE_GLOBAL_FDN_REVERB = C.SYZ_OTYPE_GLOBAL_FDN_REVERB
	OTYPE_STREAM_HANDLE = C.SYZ_OTYPE_STREAM_HANDLE
	OTYPE_AUTOMATION_BATCH = C.SYZ_OTYPE_AUTOMATION_BATCH
	OTYPE_FAST_SINE_BANK_GENERATOR = C.SYZ_OTYPE_FAST_SINE_BANK_GENERATOR
)

type PANNER_STRATEGY C.int

const (
	PANNER_STRATEGY_DELEGATE PANNER_STRATEGY = C.SYZ_PANNER_STRATEGY_DELEGATE
	PANNER_STRATEGY_HRTF = C.SYZ_PANNER_STRATEGY_HRTF
	PANNER_STRATEGY_STEREO = C.SYZ_PANNER_STRATEGY_STEREO
	PANNER_STRATEGY_COUNT = C.SYZ_PANNER_STRATEGY_COUNT
)

type DISTANCE_MODEL C.int

const (
	DISTANCE_MODEL_NONE DISTANCE_MODEL = C.SYZ_DISTANCE_MODEL_NONE
	DISTANCE_MODEL_LINEAR= C.SYZ_DISTANCE_MODEL_LINEAR
	DISTANCE_MODEL_EXPONENTIAL = C.SYZ_DISTANCE_MODEL_EXPONENTIAL
	DISTANCE_MODEL_INVERSE = C.SYZ_DISTANCE_MODEL_INVERSE
	DISTANCE_MODEL_COUNT = C.SYZ_DISTANCE_MODEL_COUNT
)

type NOISE_TYPE C.int

const (
	NOISE_TYPE_UNIFORM NOISE_TYPE = C.SYZ_NOISE_TYPE_UNIFORM
	NOISE_TYPE_VM = C.SYZ_NOISE_TYPE_VM
	NOISE_TYPE_FILTERED_BROWN = C.SYZ_NOISE_TYPE_FILTERED_BROWN
	NOISE_TYPE_COUNT = C.SYZ_NOISE_TYPE_COUNT
)

type PROPERTIES C.int

const (
	P_AZIMUTH = C.SYZ_P_AZIMUTH
	P_BUFFER = C.SYZ_P_BUFFER
	P_ELEVATION = C.SYZ_P_ELEVATION
	P_GAIN = C.SYZ_P_GAIN
	P_DEFAULT_PANNER_STRATEGY = C.SYZ_P_DEFAULT_PANNER_STRATEGY
	P_PANNING_SCALAR = C.SYZ_P_PANNING_SCALAR
	P_PLAYBACK_POSITION = C.SYZ_P_PLAYBACK_POSITION
	P_POSITION = C.SYZ_P_POSITION
	P_ORIENTATION = C.SYZ_P_ORIENTATION
	P_CLOSENESS_BOOST = C.SYZ_P_CLOSENESS_BOOST
	P_CLOSENESS_BOOST_DISTANCE = C.SYZ_P_CLOSENESS_BOOST_DISTANCE
	P_DISTANCE_MAX = C.SYZ_P_DISTANCE_MAX
	P_DISTANCE_MODEL = C.SYZ_P_DISTANCE_MODEL
	P_DISTANCE_REF = C.SYZ_P_DISTANCE_REF
	P_ROLLOFF = C.SYZ_P_ROLLOFF
	P_DEFAULT_CLOSENESS_BOOST = C.SYZ_P_DEFAULT_CLOSENESS_BOOST
	P_DEFAULT_CLOSENESS_BOOST_DISTANCE = C.SYZ_P_DEFAULT_CLOSENESS_BOOST_DISTANCE
	P_DEFAULT_DISTANCE_MAX = C.SYZ_P_DEFAULT_DISTANCE_MAX
	P_DEFAULT_DISTANCE_MODEL = C.SYZ_P_DEFAULT_DISTANCE_MODEL
	P_DEFAULT_DISTANCE_REF = C.SYZ_P_DEFAULT_DISTANCE_REF
	P_DEFAULT_ROLLOFF = C.SYZ_P_DEFAULT_ROLLOFF
	P_LOOPING = C.SYZ_P_LOOPING
	P_NOISE_TYPE = C.SYZ_P_NOISE_TYPE
	P_PITCH_BEND = C.SYZ_P_PITCH_BEND
	P_INPUT_FILTER_ENABLED = C.SYZ_P_INPUT_FILTER_ENABLED
	P_INPUT_FILTER_CUTOFF = C.SYZ_P_INPUT_FILTER_CUTOFF
	P_MEAN_FREE_PATH = C.SYZ_P_MEAN_FREE_PATH
	P_T60 = C.SYZ_P_T60
	P_LATE_REFLECTIONS_LF_ROLLOFF = C.SYZ_P_LATE_REFLECTIONS_LF_ROLLOFF
	P_LATE_REFLECTIONS_LF_REFERENCE = C.SYZ_P_LATE_REFLECTIONS_LF_REFERENCE
	P_LATE_REFLECTIONS_HF_ROLLOFF = C.SYZ_P_LATE_REFLECTIONS_HF_ROLLOFF
	P_LATE_REFLECTIONS_HF_REFERENCE = C.SYZ_P_LATE_REFLECTIONS_HF_REFERENCE
	P_LATE_REFLECTIONS_DIFFUSION = C.SYZ_P_LATE_REFLECTIONS_DIFFUSION
	P_LATE_REFLECTIONS_MODULATION_DEPTH = C.SYZ_P_LATE_REFLECTIONS_MODULATION_DEPTH
	P_LATE_REFLECTIONS_MODULATION_FREQUENCY = C.SYZ_P_LATE_REFLECTIONS_MODULATION_FREQUENCY
	P_LATE_REFLECTIONS_DELAY = C.SYZ_P_LATE_REFLECTIONS_DELAY
	P_FILTER = C.SYZ_P_FILTER
	P_FILTER_DIRECT = C.SYZ_P_FILTER_DIRECT
	P_FILTER_EFFECTS = C.SYZ_P_FILTER_EFFECTS
	P_FILTER_INPUT = C.SYZ_P_FILTER_INPUT
	P_CURRENT_TIME = C.SYZ_P_CURRENT_TIME
	P_SUGGESTED_AUTOMATION_TIME = C.SYZ_P_SUGGESTED_AUTOMATION_TIME
	P_FREQUENCY = C.SYZ_P_FREQUENCY
)

type EVENT_TYPES C.int

const (
	EVENT_TYPE_INVALID EVENT_TYPES = C.SYZ_EVENT_TYPE_INVALID
	EVENT_TYPE_LOOPED = C.SYZ_EVENT_TYPE_LOOPED
	EVENT_TYPE_FINISHED = C.SYZ_EVENT_TYPE_FINISHED
	EVENT_TYPE_USER_AUTOMATION = C.SYZ_EVENT_TYPE_USER_AUTOMATION
)

type INTERPOLATION_TYPES C.int
	INTERPOLATION_TYPE_NONE INTERPOLATION_TYPES = C.SYZ_INTERPOLATION_TYPE_NONE
	INTERPOLATION_TYPE_LINEAR = C.SYZ_INTERPOLATION_TYPE_LINEAR
)

type AUTOMATION_COMMANDS C.int

const (
	AUTOMATION_COMMAND_APPEND_PROPERTY AUTOMATION_COMMANDS = C.SYZ_AUTOMATION_COMMAND_APPEND_PROPERTY
	AUTOMATION_COMMAND_SEND_USER_EVENT = C.SYZ_AUTOMATION_COMMAND_SEND_USER_EVENT
	AUTOMATION_COMMAND_CLEAR_PROPERTY = C.SYZ_AUTOMATION_COMMAND_CLEAR_PROPERTY
	AUTOMATION_COMMAND_CLEAR_EVENTS = C.SYZ_AUTOMATION_COMMAND_CLEAR_EVENTS
	AUTOMATION_COMMAND_CLEAR_ALL_PROPERTIES = C.SYZ_AUTOMATION_COMMAND_CLEAR_ALL_PROPERTIES
)
